[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm>=6.2"]
build-backend = "setuptools.build_meta"[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Eng's OpenML V2"
version = "0.1.0"
dependencies = [
    "numpy>=1.20.0",
]